"""Video gateway: the only place that turns stored source records into
VideoSource objects, validates them, and manages temporary media.

Responsibilities (see architecture diagram):
  * source manager   - build/validate sources per kind
  * video metadata   - validation metadata + optional ffprobe details
  * clip management  - temporary media in VIDEO_WORK_DIR, released after use
"""

from __future__ import annotations

import asyncio
import json
import logging
import shutil
from pathlib import Path
from typing import Any

from app.core.config import Settings
from app.core.errors import NotSupportedYet, ValidationFailed
from app.video.sources.base import MediaHandle, SourceKind, TimeWindow, VideoSource
from app.video.sources.live import NvrChannelSource, OnvifCameraSource, RtspCameraSource
from app.video.sources.local_source import LocalFileVideoSource
from app.video.sources.upload_source import UploadedVideoSource
from app.video.sources.url_source import UrlVideoSource
from app.video.url_safety import UrlPolicy

logger = logging.getLogger(__name__)


class VideoGateway:
    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.policy = UrlPolicy(allowed_domains=tuple(settings.video_url_allowed_domains), allow_http=settings.video_url_allow_http)
        self.workdir = settings.video_work_dir.resolve()

    def enabled_kinds(self) -> list[SourceKind]:
        kinds = [SourceKind.URL]
        if self.settings.enable_video_uploads:
            kinds.append(SourceKind.UPLOAD)
        if self.settings.enable_local_video_sources:
            kinds.append(SourceKind.LOCAL)
        return kinds

    def build(self, kind: str, uri: str, *, source_id: Any = None, metadata: dict[str, Any] | None = None) -> VideoSource:
        try:
            source_kind = SourceKind(kind)
        except ValueError as exc:
            raise ValidationFailed(f"Unknown source type: {kind}") from exc

        if source_kind is SourceKind.URL:
            return UrlVideoSource(source_id, uri, metadata, policy=self.policy, max_bytes=self.settings.max_download_bytes)
        if source_kind is SourceKind.UPLOAD:
            # Upload paths are generated by the server (see upload_source.store_upload), never user-supplied.
            return UploadedVideoSource(source_id, uri, metadata, root=self.settings.upload_dir)
        if source_kind is SourceKind.LOCAL:
            if not self.settings.enable_local_video_sources:
                raise ValidationFailed("Local video files are disabled on this server")
            return LocalFileVideoSource(source_id, uri, metadata, root=self.settings.local_video_dir)
        live = {SourceKind.RTSP: RtspCameraSource, SourceKind.ONVIF: OnvifCameraSource, SourceKind.NVR: NvrChannelSource}
        if source_kind in live:
            raise NotSupportedYet(f"{source_kind.value.upper()} cameras are not supported yet. Phase 1 supports video URLs.")
        raise ValidationFailed(f"Unsupported source type: {kind}")

    async def validate(self, source: VideoSource) -> dict[str, Any]:
        return await source.validate()

    async def acquire(self, source: VideoSource, window: TimeWindow | None = None) -> MediaHandle:
        media = await source.acquire_media(self.workdir, window)
        if media.local_path is not None:
            media.metadata.update(await probe(media.local_path))
        return media

    def purge_workdir(self) -> None:
        """Remove leftover temp media (e.g. after a crash). Called on startup."""
        if self.workdir.exists():
            for item in self.workdir.iterdir():
                if item.is_file() and item.suffix == ".video":
                    item.unlink(missing_ok=True)


async def probe(path: Path) -> dict[str, Any]:
    """Read duration/resolution with ffprobe if it is installed. Optional."""
    ffprobe = shutil.which("ffprobe")
    if ffprobe is None:
        return {}
    try:
        proc = await asyncio.create_subprocess_exec(
            ffprobe, "-v", "error", "-print_format", "json", "-show_format", "-show_streams", str(path),
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL,
        )
        stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=30)
        data = json.loads(stdout or b"{}")
    except (OSError, TimeoutError, json.JSONDecodeError) as exc:
        logger.warning("ffprobe failed: %s", exc)
        return {}
    video = next((s for s in data.get("streams", []) if s.get("codec_type") == "video"), {})
    info: dict[str, Any] = {}
    if duration := data.get("format", {}).get("duration"):
        info["duration_seconds"] = round(float(duration), 2)
    if video:
        info.update({"width": video.get("width"), "height": video.get("height"), "codec": video.get("codec_name")})
    return info
