"""The media server (MediaMTX) behind Visionary live video.

    camera RTSP ──pull──▶ MediaMTX path cam/<camera>/<main|sub> ──▶ WebRTC (WHEP) / HLS to browsers and phones
    gateway    ──push──▶ MediaMTX path gw/<gateway>/<camera>/<role>          ──▶ recording (fMP4) + playback API
                                                        └──▶ rtsp://127.0.0.1 for the live AI workers

Security: MediaMTX asks Visionary (POST /api/media/auth) before every read, publish or playback:
  * browsers present a short-lived stream token (JWT, one camera path, 5 minutes), never a camera password
  * gateways publish only under gw/<their id>/ with their own secret
  * the backend's AI workers use an internal credential derived from SECRET_KEY
Camera passwords are only sent to MediaMTX's local API (127.0.0.1) as part of the pull source URL.
"""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import logging
import subprocess
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any
from urllib.parse import quote

import httpx
import jwt

from app.cameras.credentials import redact
from app.core.config import Settings, get_settings

logger = logging.getLogger(__name__)
INTERNAL_USER = "visionary-internal"
STREAM_TOKEN_TTL = timedelta(minutes=5)
_process: subprocess.Popen[bytes] | None = None


def internal_password(settings: Settings | None = None) -> str:
    s = settings or get_settings()
    return hmac.new(s.secret_key.get_secret_value().encode(), b"media-internal", hashlib.sha256).hexdigest()[:32]


def camera_path(source_id: uuid.UUID, role: str = "main") -> str:
    return f"cam/{source_id.hex}/{role}"


def gateway_path(gateway_id: uuid.UUID, source_id: uuid.UUID, role: str = "main") -> str:
    return f"gw/{gateway_id.hex}/{source_id.hex}/{role}"


def internal_rtsp_url(path: str, settings: Settings | None = None) -> str:
    s = settings or get_settings()
    return f"rtsp://{INTERNAL_USER}:{internal_password(s)}@127.0.0.1:{s.media_rtsp_port}/{path}"


# -------------------------------------------------------------------------------- stream tokens
def stream_token(user_id: uuid.UUID, path_prefix: str, actions: tuple[str, ...] = ("read",), ttl: timedelta = STREAM_TOKEN_TTL) -> str:
    s = get_settings()
    now = datetime.now(UTC)
    payload = {"typ": "stream", "sub": str(user_id), "path": path_prefix, "act": list(actions), "iat": now, "exp": now + ttl}
    return jwt.encode(payload, s.secret_key.get_secret_value(), algorithm="HS256")


def check_stream_token(token: str, path: str, action: str) -> str | None:
    """User id if the token allows `action` on `path`, else None."""
    try:
        payload = jwt.decode(token, get_settings().secret_key.get_secret_value(), algorithms=["HS256"])
    except jwt.PyJWTError:
        return None
    if payload.get("typ") != "stream" or action not in payload.get("act", []):
        return None
    prefix = payload.get("path", "")
    if not prefix or not (path == prefix or path.startswith(prefix.rstrip("/") + "/")):
        return None
    return payload.get("sub")


# -------------------------------------------------------------------------------- process + config
def config_text(s: Settings) -> str:
    ice = "\n".join(_ice_entry(u) for u in s.media_ice_servers) or ""
    return f"""# Generated by Visionary (app/cameras/media_server.py). Do not edit: regenerated at startup.
logLevel: warn
logDestinations: [stdout]
authMethod: http
authHTTPAddress: {s.media_backend_url}/api/media/auth
authHTTPExclude:
  - action: api
  - action: metrics
api: true
apiAddress: 127.0.0.1:{s.media_api_port}
metrics: true
metricsAddress: 127.0.0.1:9998
playback: true
playbackAddress: :{s.media_playback_port}
rtsp: true
rtspAddress: :{s.media_rtsp_port}
rtspTransports: [tcp]
rtmp: false
srt: false
moq: false
hls: true
hlsAddress: :{s.media_hls_port}
hlsVariant: lowLatency
hlsAllowOrigins: ['*']
webrtc: true
webrtcAddress: :{s.media_webrtc_port}
webrtcLocalUDPAddress: :{s.media_webrtc_udp_port}
webrtcAllowOrigins: ['*']
webrtcICEServers2:{' []' if not ice else chr(10) + ice}
pathDefaults:
  recordPath: {s.recording_dir.resolve().as_posix()}/%path/%Y-%m-%d_%H-%M-%S-%f
  recordFormat: fmp4
  recordSegmentDuration: 10m
  recordDeleteAfter: {s.recording_retention}
paths:
  # gateway uploads: gw/<gateway>/<camera>/<role>, any published stream is accepted (auth decides who)
  "~^gw/":
    source: publisher
"""


def _ice_entry(url: str) -> str:
    # turn:user:pass@host:port -> url + credentials; stun:host:port -> url only
    if url.startswith(("turn:", "turns:")) and "@" in url:
        scheme, rest = url.split(":", 1)
        creds, host = rest.rsplit("@", 1)
        user, _, password = creds.partition(":")
        return f"  - url: {scheme}:{host}\n    username: {user}\n    password: {password}"
    return f"  - url: {url}"


def start(settings: Settings | None = None) -> None:
    """Start MediaMTX as a child process (MEDIA_SERVER_MANAGED=true)."""
    global _process
    s = settings or get_settings()
    if _process is not None and _process.poll() is None:
        return
    exe = s.media_server_exe.resolve()
    if not exe.exists():
        logger.warning("MediaMTX not found at %s: live video is disabled", exe)
        return
    import socket

    from app.cameras.proc import bind_children_to_this_process, preexec

    with socket.socket() as probe:
        probe.settimeout(0.5)
        if probe.connect_ex(("127.0.0.1", s.media_api_port)) == 0:
            logger.error("Port %s is already in use (a media server left over from a crash?). Stop it and restart Visionary: "
                         "live video would otherwise use its old settings.", s.media_api_port)
            return
    bind_children_to_this_process()  # the media server and ffmpeg die with this process: no orphans holding the ports
    cfg = Path("./data/mediamtx.yml").resolve()
    cfg.parent.mkdir(parents=True, exist_ok=True)
    s.recording_dir.mkdir(parents=True, exist_ok=True)
    cfg.write_text(config_text(s))
    log = open(cfg.parent / "mediamtx.log", "ab")  # noqa: SIM115 - lives as long as the process
    _process = subprocess.Popen([str(exe), str(cfg)], stdout=log, stderr=subprocess.STDOUT, cwd=str(cfg.parent), preexec_fn=preexec())
    logger.info("Media server started (pid %s): RTSP :%s, WebRTC :%s, HLS :%s", _process.pid, s.media_rtsp_port, s.media_webrtc_port, s.media_hls_port)


def stop() -> None:
    global _process
    if _process is not None and _process.poll() is None:
        _process.terminate()
        try:
            _process.wait(5)
        except subprocess.TimeoutExpired:
            _process.kill()
    _process = None


def running() -> bool:
    return _process is not None and _process.poll() is None


async def healthy() -> bool:
    """The media server answers its control API (whoever started it)."""
    try:
        return (await _request("GET", f"{_api()}/paths/list?itemsPerPage=1")).status_code == 200
    except httpx.HTTPError:
        return False


# -------------------------------------------------------------------------------- API
def _api(s: Settings | None = None) -> str:
    return f"http://127.0.0.1:{(s or get_settings()).media_api_port}/v3"


async def _request(method: str, url: str, **kw: Any) -> httpx.Response:
    async with httpx.AsyncClient(timeout=5, trust_env=False) as client:
        return await client.request(method, url, **kw)


async def ensure_path(name: str, source: str, *, record: bool = False, on_demand: bool = False) -> None:
    """Create or update a pulled path (source = camera URL, may contain credentials: local API only)."""
    body = {"source": source, "sourceOnDemand": on_demand, "rtspTransport": "tcp", "record": record}
    try:
        r = await _request("POST", f"{_api()}/config/paths/add/{quote(name, safe='/')}", json=body)
        if r.status_code == 400 and "already exists" in r.text:
            r = await _request("PATCH", f"{_api()}/config/paths/patch/{quote(name, safe='/')}", json=body)
        if r.status_code >= 300:
            raise RuntimeError(redact(r.text)[:200])
    except httpx.HTTPError as exc:
        raise RuntimeError(f"media server not reachable: {exc}") from exc


async def ensure_web_path(name: str, input_path: str, height: int | None = None) -> None:
    """An H.264 copy of an H.265-only camera for browsers without H.265 WebRTC. Transcoded on demand: ffmpeg
    runs only while someone watches (NVENC when available), and stops 10 s after the last viewer leaves."""
    from app.video import ffmpeg

    s = get_settings()
    enc = "-c:v h264_nvenc -preset p4 -tune ll -rc cbr -b:v 2M" if ffmpeg.nvenc_available() else "-c:v libx264 -preset veryfast -tune zerolatency -b:v 1500k"
    # -loglevel quiet: ffmpeg error lines include the internal URL (with its password) and would land in the media log
    scale = f"-vf scale=-2:{min(720, height)} " if height else ""
    cmd = (f'"{ffmpeg.ffmpeg_exe()}" -hide_banner -loglevel quiet -rtsp_transport tcp -i {internal_rtsp_url(input_path, s)} -an '
           f"{scale}{enc} -g 50 -bf 0 -pix_fmt yuv420p -f rtsp -rtsp_transport tcp "
           f"rtsp://{INTERNAL_USER}:{internal_password(s)}@127.0.0.1:{s.media_rtsp_port}/$MTX_PATH")
    body = {"source": "publisher", "runOnDemand": cmd, "runOnDemandRestart": True, "runOnDemandCloseAfter": "10s", "runOnDemandStartTimeout": "15s"}
    try:
        r = await _request("POST", f"{_api()}/config/paths/add/{quote(name, safe='/')}", json=body)
        if r.status_code == 400 and "already exists" in r.text:
            r = await _request("PATCH", f"{_api()}/config/paths/patch/{quote(name, safe='/')}", json=body)
        if r.status_code >= 300:
            raise RuntimeError(r.text[:200])
    except httpx.HTTPError as exc:
        raise RuntimeError(f"media server not reachable: {exc}") from exc


async def ensure_publisher_path(name: str, *, record: bool = False) -> None:
    body = {"source": "publisher", "record": record}
    r = await _request("POST", f"{_api()}/config/paths/add/{quote(name, safe='/')}", json=body)
    if r.status_code == 400 and "already exists" in r.text:
        await _request("PATCH", f"{_api()}/config/paths/patch/{quote(name, safe='/')}", json=body)


async def remove_path(name: str) -> None:
    try:
        await _request("DELETE", f"{_api()}/config/paths/delete/{quote(name, safe='/')}")
    except httpx.HTTPError:
        pass


async def path_state(name: str) -> dict[str, Any] | None:
    """Live state of a path: ready, bytes received, readers, tracks (None if the media server has no such path)."""
    try:
        r = await _request("GET", f"{_api()}/paths/get/{quote(name, safe='/')}")
    except httpx.HTTPError:
        return None
    if r.status_code != 200:
        return None
    d = r.json()
    return {"ready": bool(d.get("ready")), "bytes_received": d.get("bytesReceived", 0), "bytes_sent": d.get("bytesSent", 0),
            "readers": len(d.get("readers") or []), "tracks": [t.get("codec") if isinstance(t, dict) else t for t in (d.get("tracks2") or d.get("tracks") or [])],
            "ready_time": d.get("readyTime")}


async def all_paths() -> list[dict[str, Any]]:
    try:
        r = await _request("GET", f"{_api()}/paths/list?itemsPerPage=1000")
        return r.json().get("items", []) if r.status_code == 200 else []
    except httpx.HTTPError:
        return []


async def webrtc_sessions() -> list[dict[str, Any]]:
    try:
        r = await _request("GET", f"{_api()}/webrtcsessions/list?itemsPerPage=1000")
        return r.json().get("items", []) if r.status_code == 200 else []
    except httpx.HTTPError:
        return []


async def recordings(path: str) -> list[dict[str, Any]]:
    """Recorded time spans of a path (MediaMTX playback server)."""
    s = get_settings()
    try:
        async with httpx.AsyncClient(timeout=10, trust_env=False) as client:
            r = await client.get(f"http://127.0.0.1:{s.media_playback_port}/list", params={"path": path}, auth=(INTERNAL_USER, internal_password(s)))
    except httpx.HTTPError:
        return []
    return r.json() if r.status_code == 200 else []


def playback_url(path: str, start: datetime, duration: float) -> str:
    s = get_settings()
    return (f"http://127.0.0.1:{s.media_playback_port}/get?path={quote(path, safe='')}&start={quote(start.isoformat(), safe='')}"
            f"&duration={duration:.3f}&format=mp4")


async def wait_api(timeout: float = 10.0) -> bool:
    """Wait until the media server's control API answers (after start())."""
    deadline = asyncio.get_running_loop().time() + timeout
    while asyncio.get_running_loop().time() < deadline:
        try:
            r = await _request("GET", f"{_api()}/paths/list")
            if r.status_code == 200:
                return True
        except httpx.HTTPError:
            pass
        await asyncio.sleep(0.3)
    return False


async def wait_ready(name: str, timeout: float = 15.0) -> bool:
    deadline = asyncio.get_running_loop().time() + timeout
    while asyncio.get_running_loop().time() < deadline:
        st = await path_state(name)
        if st and st["ready"]:
            return True
        await asyncio.sleep(0.5)
    return False
